
stages:
  - Validate
  - Test
  - Deploy

before_script:
  - composer install


Validate Classes:
  tags:
    - integrate
  stage: Validate

  script:
    - find . -name *.php exec php -l {} \;


Run Test:
  tags:
    - integrate
  stage: Test 
  script:
    - ./vendor/bin/phpunit Test/RandomTest.php

Deploy:
  tags: 
    - deploy
  stage: Deploy 
  script:
    - docker build . -t local/phpapp
    - docker rm -f phpapp 
    - docker run -d -p 8080:80 --name phpapp --rm local/phpapp



