
stages:
  - validate
  - test
  - deploy

before_script:
  - composer install


Validate Classes:
  tags:
    - integrate
  stage: validate

  script:
    - php -l Classes/RandomNumber.php



Run Test:
  tags:
    - integrate
  stage: test 
  script:
    - ./vendor/bin/phpunit Test/RandomTest.php


